version: '3.5'
services:

  rabbit-mq:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    volumes:
      - ./rabbitmqdata:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./redis_data:/data

  data-httpserver:
    depends_on:
      - redis
      - rabbit-mq
    image: mengwei2275/datasource-data:v0.0.2
    restart: always
    volumes:
      - "./data/config/:/config/data/"
    command: httpserver

  data-worker:
    depends_on:
      - redis
      - rabbit-mq
    image: mengwei2275/datasource-data:v0.0.2
    restart: always
    volumes:
      - "./data/config/:/config/data/"
    command: worker-server

  auth-httpserver:
    depends_on:
      - redis
      - rabbit-mq
    image: mengwei2275/datasource-auth:v0.0.2
    restart: always
    volumes:
      - "./auth/config/:/config/auth/"
    command: httpserver


networks:
  default:
    name: datasource
    driver: bridge