FROM ubuntu:18.04

RUN mkdir /config
RUN mkdir /config/data

COPY ./dist/data /bin

RUN mkdir log   && ls /bin/    && chmod +x /bin/data

EXPOSE 9030

ENTRYPOINT ["/bin/data", "--config=/config/data/dev-local.json"]