name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1


    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi


    - name: set go path
      run: |
        GOPATH=$GOPATH:/home/runner/work/datasource/
        mkdir ../src
        cp -rf ../datasource ../src/
        ln -sv /home/runner/work/datasource/datasource/ /home/runner/work/datasource/datasource/vendor/

    - name: Build
      run: |
        GOPATH=$GOPATH:/home/runner/work/datasource/ && go build -o auth1 apps/auth/auth.go
        GOPATH=$GOPATH:/home/runner/work/datasource/ && go build -o data1 apps/data/data.go

    - name: Test
      run: |
        chmod +x auth1
        chmod +x data1
        ./auth1 -h
        ./data1 -h
