name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

#    - name: Check out code into the Go module directory
#      uses: actions/checkout@v1

    - name: set go path
      run: GOPATH=$GOPATH:/home/runner/work/datasource/

    - name: create src
      run: mkdir ../src

    - name: copy to gopath
      run: cp -rf ../datasource ../src/

    - name: Build
      run: pwd && go build -o auth1 ./apps/auth/auth.go
